# Generated by Django 4.2.2 on 2023-06-16 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0002_boards_columns_elements_delete_element'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Elements',
            new_name='Tasks',
        ),
        migrations.AlterField(
            model_name='tasks',
            name='fcolumn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.boards'),
        ),
        migrations.DeleteModel(
            name='Columns',
        ),
    ]
