# Generated by Django 4.2.2 on 2023-06-19 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_tasks_asigneduser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='asigneduser',
        ),
    ]
