# Generated by Django 4.2.2 on 2023-06-22 21:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0008_tasks_asigneduser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Asigments',
            new_name='Assignments',
        ),
    ]
