# Generated by Django 4.2.2 on 2023-06-22 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_rename_asigments_assignments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='asigneduser',
            new_name='assigneduser',
        ),
    ]
