# Generated by Django 4.2.2 on 2023-06-23 21:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0010_rename_asigneduser_tasks_assigneduser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Assignments',
            new_name='Asigments',
        ),
    ]
